postsubmits:
  vagator/test-infra:
  - name: push-image-builder
    cluster: test-jobs
    decorate: true
    max_concurrency: 1
    branches:
    - ^main$
    run_if_changed: '^images/image-build*'
    annotations:
      testgrid-dashboards: build-images
      testgrid-tab-name: image-builder
    labels:
      preset-registry-credentials: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: public.ecr.aws/t0q8k6g2/vagator/image-builder:v1
        command:
        - images/image-builder/run.sh
        args:
        - images/image-builder
        - public.ecr.aws/t0q8k6g2/vagator/image-builder
        securityContext:
          privileged: true

