postsubmits:
  vagator/test-prow:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  vagator/test-prow:
  - name: test-presubmit
    cluster: test-jobs
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
