postsubmits:
  vagator/test-prow:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  vagator/test-prow:
  - name: test-presubmit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
periodics:
- name: default-cluster
  cluster: default
  interval: 10m
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
- name: jobs-cluster
  cluster: test-jobs
  interval: 10m
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/printenv"]
