postsubmits:
  vagator/test-prow:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  vagator/test-prow:
  - name: test-presubmit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
periodics:
- interval: 10m
  name: echo-test-4
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
