periodics:
- name: periodic-build-tce
  decorate: true
  interval: 24h
  extra_refs:
  - org: vagator
    repo: test-infra
    base_ref: main
  annotations:
    testgrid-dashboards: tce
    testgrid-tab-name: periodics
  labels:
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: public.ecr.aws/t0q8k6g2/vagator/test-image:v20220803-82253a6
      command:
      - /usr/local/bin/run.sh
      args:
      - vmware-tanzu
      - community-edition
      - make docker-management-and-cluster-e2e-test
      securityContext:
        privileged: true

