periodics:
- name: periodic-build-tce
  decorate: true
  interval: 24h
  extra_refs:
  - org: vagator
    repo: test-infra
    base_ref: main
  annotations:
    testgrid-dashboards: tce
    testgrid-tab-name: periodics
  labels:
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: public.ecr.aws/t0q8k6g2/vagator/test-image:v20220803-82253a6
      command:
      - /usr/local/bin/run.sh
      args:
      - vmware-tanzu
      - community-edition
      - make docker-management-and-cluster-e2e-test
      securityContext:
        privileged: true
- name: periodic-build-tce-with-boskos-test
  decorate: true
  cron: 0/30 * * * *
  extra_refs:
  - org: vagator
    repo: test-infra
    base_ref: main
  annotations:
    testgrid-dashboards: tce
    testgrid-tab-name: periodics
  labels:
    preset-aws-credential: "true"
    preset-kind-volume-mounts: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: public.ecr.aws/t0q8k6g2/vagator/test-image:v20221003-6f693ab
      command:
      - python3 /usr/local/bin/boskos.py --help
      - /usr/local/bin/run.sh
      args:
      - vmware-tanzu
      - community-edition
      - make docker-management-and-cluster-e2e-test
      env:
        - name: BOSKOS_HOST
          value: "boskos.test-pods.svc.cluster.local"
      securityContext:
        privileged: true
